# .streamlit/secrets.toml

SUPABASE_URL = "https://ggqnlqhncarooowdgfpo.supabase.co"
SUPABASE_KEY   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncW5scWhuY2Fyb29vd2RnZnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzI0NjEsImV4cCI6MjA2ODAwODQ2MX0.9pstmAkEgL1O6R5ObQZ1QxOcrqTYSdtRfa_xfX5PVZY"